#!/bin/bash

userresources=$HOME/.config/xresources/.Xresources
usermodmap=$HOME/.Xmodmap

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

xset fp rehash
xset dpms 30000 30000 30000
xset s 30000 30000
xset -b
xhost +localhost
xcape -e 'Control_L=Escape'
xbindkeys
dunst &

exec i3

